import Head from 'next/head'
import HomeView from './HomeView'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='bg-site bg-no-repeat bg-cover overflow-hidden h-screen'>
          <HomeView />
        </div>
      </main>
    </>
  )
}
